package com.gz.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_attachment", "id", Attachment.class);
		arp.addMapping("tb_category", "id", Category.class);
		arp.addMapping("tb_company", "id", Company.class);
		arp.addMapping("tb_dept", "id", Dept.class);
		arp.addMapping("tb_device", "id", Device.class);
		arp.addMapping("tb_device_class", "id", DeviceClass.class);
		arp.addMapping("tb_field", "id", Field.class);
		arp.addMapping("tb_lanmu", "id", Lanmu.class);
		arp.addMapping("tb_module", "id", Module.class);
		arp.addMapping("tb_order", "id", Order.class);
		arp.addMapping("tb_parameter", "id", Parameter.class);
		arp.addMapping("tb_product", "id", Product.class);
		arp.addMapping("tb_promotion", "id", Promotion.class);
		arp.addMapping("tb_region", "id", Region.class);
		arp.addMapping("tb_role", "id", Role.class);
		arp.addMapping("tb_role_lanmu", "id", RoleLanmu.class);
		arp.addMapping("tb_stock", "id", Stock.class);
		arp.addMapping("tb_stock_in", "id", StockIn.class);
		arp.addMapping("tb_stock_in_detail", "id", StockInDetail.class);
		arp.addMapping("tb_user", "id", User.class);
		arp.addMapping("tb_user_bak", "id", UserBak.class);
		arp.addMapping("tb_warehouse", "id", Warehouse.class);
	}
}

