package com.gz.common.model;

import com.gz.common.model.base.BaseDeviceClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceClass extends BaseDeviceClass<DeviceClass> {
	public static final DeviceClass dao = new DeviceClass().dao();
}
