package com.gz.common.model;

import com.gz.common.model.base.BaseModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Module extends BaseModule<Module> {
	public static final Module dao = new Module().dao();
}
