package com.gz.common.model;

import com.gz.common.model.base.BaseOrderProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderProduct extends BaseOrderProduct<OrderProduct> {
	public static final OrderProduct dao = new OrderProduct().dao();
}
