package com.gz.common.model;

import com.gz.common.model.base.BasePay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pay extends BasePay<Pay> {
	public static final Pay dao = new Pay().dao();
}
