package com.gz.common.model;

import com.gz.common.model.base.BaseStockInDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockInDetail extends BaseStockInDetail<StockInDetail> {
	public static final StockInDetail dao = new StockInDetail().dao();
}
