package com.gz.common.model;

import com.gz.common.model.base.BaseStockIn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockIn extends BaseStockIn<StockIn> {
	public static final StockIn dao = new StockIn().dao();
}
