package com.gz.common.model;

import com.gz.common.model.base.BaseUserCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCoupon extends BaseUserCoupon<UserCoupon> {
	public static final UserCoupon dao = new UserCoupon().dao();
}
