package com.gz.common.model;

import com.gz.common.model.base.BaseUserBak;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBak extends BaseUserBak<UserBak> {
	public static final UserBak dao = new UserBak().dao();
}
