package com.gz.common.model;

import com.gz.common.model.base.BaseXiaochengxu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Xiaochengxu extends BaseXiaochengxu<Xiaochengxu> {
	public static final Xiaochengxu dao = new Xiaochengxu().dao();
}
