package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserAccount(java.lang.String userAccount) {
		set("userAccount", userAccount);
		return (M)this;
	}
	
	public java.lang.String getUserAccount() {
		return getStr("userAccount");
	}

	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setDeptId(java.lang.Integer deptId) {
		set("deptId", deptId);
		return (M)this;
	}
	
	public java.lang.Integer getDeptId() {
		return getInt("deptId");
	}

	public M setDeptPath(java.lang.String deptPath) {
		set("deptPath", deptPath);
		return (M)this;
	}
	
	public java.lang.String getDeptPath() {
		return getStr("deptPath");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
		return (M)this;
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("roleId");
	}

	public M setRegistDatetime(java.util.Date registDatetime) {
		set("registDatetime", registDatetime);
		return (M)this;
	}
	
	public java.util.Date getRegistDatetime() {
		return get("registDatetime");
	}

	public M setLastDatetime(java.util.Date lastDatetime) {
		set("lastDatetime", lastDatetime);
		return (M)this;
	}
	
	public java.util.Date getLastDatetime() {
		return get("lastDatetime");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
