package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePay<M extends BasePay<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public M setPayMoney(java.lang.Double payMoney) {
		set("pay_money", payMoney);
		return (M)this;
	}
	
	public java.lang.Double getPayMoney() {
		return getDouble("pay_money");
	}

	public M setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
		return (M)this;
	}
	
	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public M setPayWay(java.lang.String payWay) {
		set("pay_way", payWay);
		return (M)this;
	}
	
	public java.lang.String getPayWay() {
		return getStr("pay_way");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
		return (M)this;
	}
	
	public java.lang.String getTradeNo() {
		return getStr("trade_no");
	}

	public M setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
		return (M)this;
	}
	
	public java.lang.String getTransactionId() {
		return getStr("transaction_id");
	}

	public M setStatues(java.lang.Integer statues) {
		set("statues", statues);
		return (M)this;
	}
	
	public java.lang.Integer getStatues() {
		return getInt("statues");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setRefundMoney(java.lang.Double refundMoney) {
		set("refund_money", refundMoney);
		return (M)this;
	}
	
	public java.lang.Double getRefundMoney() {
		return getDouble("refund_money");
	}

	public M setYouhuiName(java.lang.String youhuiName) {
		set("youhui_name", youhuiName);
		return (M)this;
	}
	
	public java.lang.String getYouhuiName() {
		return getStr("youhui_name");
	}

	public M setYouhuiMoney(java.lang.Double youhuiMoney) {
		set("youhui_money", youhuiMoney);
		return (M)this;
	}
	
	public java.lang.Double getYouhuiMoney() {
		return getDouble("youhui_money");
	}

	public M setDaijinquanMoney(java.lang.Double daijinquanMoney) {
		set("daijinquan_money", daijinquanMoney);
		return (M)this;
	}
	
	public java.lang.Double getDaijinquanMoney() {
		return getDouble("daijinquan_money");
	}

	public M setUserCouponId(java.lang.Integer userCouponId) {
		set("user_coupon_id", userCouponId);
		return (M)this;
	}
	
	public java.lang.Integer getUserCouponId() {
		return getInt("user_coupon_id");
	}

}
