package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStockInDetail<M extends BaseStockInDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setBillNo(java.lang.String billNo) {
		set("billNo", billNo);
		return (M)this;
	}
	
	public java.lang.String getBillNo() {
		return getStr("billNo");
	}

	public M setDeviceId(java.lang.Integer deviceId) {
		set("deviceId", deviceId);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceId() {
		return getInt("deviceId");
	}

	public M setQuantity(java.lang.Double quantity) {
		set("quantity", quantity);
		return (M)this;
	}
	
	public java.lang.Double getQuantity() {
		return getDouble("quantity");
	}

	public M setPrice(java.lang.Double price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public M setAmount(java.lang.Double amount) {
		set("amount", amount);
		return (M)this;
	}
	
	public java.lang.Double getAmount() {
		return getDouble("amount");
	}

	public M setReceivedNum(java.lang.Double receivedNum) {
		set("receivedNum", receivedNum);
		return (M)this;
	}
	
	public java.lang.Double getReceivedNum() {
		return getDouble("receivedNum");
	}

	public M setReceiveNum(java.lang.Double receiveNum) {
		set("receiveNum", receiveNum);
		return (M)this;
	}
	
	public java.lang.Double getReceiveNum() {
		return getDouble("receiveNum");
	}

	public M setReceiveDate(java.util.Date receiveDate) {
		set("receiveDate", receiveDate);
		return (M)this;
	}
	
	public java.util.Date getReceiveDate() {
		return get("receiveDate");
	}

}
