package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseXiaochengxu<M extends BaseXiaochengxu<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAppID(java.lang.String AppID) {
		set("AppID", AppID);
		return (M)this;
	}
	
	public java.lang.String getAppID() {
		return getStr("AppID");
	}

	public M setAppSecret(java.lang.String AppSecret) {
		set("AppSecret", AppSecret);
		return (M)this;
	}
	
	public java.lang.String getAppSecret() {
		return getStr("AppSecret");
	}

}
